import { db } from '@/db';
import { hourLogs } from '@/db/schema';

async function main() {
    const sampleHourLogs = [
        {
            userId: 2,
            date: '2024-11-15',
            serviceCategory: 'DJ',
            eventType: 'Wedding',
            clientName: 'Smith Wedding',
            venue: 'Grand Ballroom',
            startTime: '18:00',
            endTime: '23:00',
            totalHours: 5.0,
            notes: 'Equipment setup took extra time',
            status: 'approved',
            createdAt: new Date('2024-11-15T18:00:00').toISOString(),
            updatedAt: new Date('2024-11-16T09:30:00').toISOString(),
        },
        {
            userId: 3,
            date: '2024-11-18',
            serviceCategory: 'Videographer',
            eventType: 'Wedding',
            clientName: 'Johnson Anniversary',
            venue: 'Riverside Hotel',
            startTime: '14:00',
            endTime: '22:00',
            totalHours: 8.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2024-11-18T14:00:00').toISOString(),
            updatedAt: new Date('2024-11-19T10:15:00').toISOString(),
        },
        {
            userId: 4,
            date: '2024-11-22',
            serviceCategory: 'Photographer',
            eventType: 'Corporate',
            clientName: 'ABC Corp Holiday Party',
            venue: 'Downtown Convention Center',
            startTime: '17:00',
            endTime: '21:00',
            totalHours: 4.0,
            notes: null,
            status: 'pending',
            createdAt: new Date('2024-11-22T17:00:00').toISOString(),
            updatedAt: new Date('2024-11-22T17:00:00').toISOString(),
        },
        {
            userId: 5,
            date: '2024-11-25',
            serviceCategory: 'DJ',
            eventType: 'Private Party',
            clientName: 'Thompson Birthday Party',
            venue: 'Oak Tree Estate',
            startTime: '19:00',
            endTime: '23:30',
            totalHours: 4.5,
            notes: 'Client requested overtime',
            status: 'approved',
            createdAt: new Date('2024-11-25T19:00:00').toISOString(),
            updatedAt: new Date('2024-11-26T11:20:00').toISOString(),
        },
        {
            userId: 6,
            date: '2024-11-28',
            serviceCategory: 'Videographer',
            eventType: 'Wedding',
            clientName: 'Brown Bar Mitzvah',
            venue: 'Lakeview Manor',
            startTime: '15:00',
            endTime: '22:30',
            totalHours: 7.5,
            notes: null,
            status: 'approved',
            createdAt: new Date('2024-11-28T15:00:00').toISOString(),
            updatedAt: new Date('2024-11-29T08:45:00').toISOString(),
        },
        {
            userId: 7,
            date: '2024-12-02',
            serviceCategory: 'Photographer',
            eventType: 'Wedding',
            clientName: 'Davis Wedding',
            venue: 'City Hall Ballroom',
            startTime: '13:00',
            endTime: '20:00',
            totalHours: 7.0,
            notes: 'Travel delay due to traffic',
            status: 'rejected',
            createdAt: new Date('2024-12-02T13:00:00').toISOString(),
            updatedAt: new Date('2024-12-03T14:30:00').toISOString(),
        },
        {
            userId: 2,
            date: '2024-12-05',
            serviceCategory: 'DJ',
            eventType: 'Corporate',
            clientName: 'TechStart Annual Gala',
            venue: 'Garden Terrace',
            startTime: '18:30',
            endTime: '23:30',
            totalHours: 5.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2024-12-05T18:30:00').toISOString(),
            updatedAt: new Date('2024-12-06T10:00:00').toISOString(),
        },
        {
            userId: 3,
            date: '2024-12-08',
            serviceCategory: 'Videographer',
            eventType: 'Wedding',
            clientName: 'Wilson 50th Anniversary',
            venue: 'Sunset Pavilion',
            startTime: '16:00',
            endTime: '22:00',
            totalHours: 6.0,
            notes: null,
            status: 'pending',
            createdAt: new Date('2024-12-08T16:00:00').toISOString(),
            updatedAt: new Date('2024-12-08T16:00:00').toISOString(),
        },
        {
            userId: 4,
            date: '2024-12-12',
            serviceCategory: 'Photographer',
            eventType: 'Wedding',
            clientName: 'Garcia Wedding Ceremony',
            venue: 'Heritage Hall',
            startTime: '12:00',
            endTime: '19:30',
            totalHours: 7.5,
            notes: 'Additional coverage requested on-site',
            status: 'approved',
            createdAt: new Date('2024-12-12T12:00:00').toISOString(),
            updatedAt: new Date('2024-12-13T09:15:00').toISOString(),
        },
        {
            userId: 5,
            date: '2024-12-15',
            serviceCategory: 'DJ',
            eventType: 'Private Party',
            clientName: 'Lee Family Reunion',
            venue: 'The Country Club',
            startTime: '17:00',
            endTime: '22:00',
            totalHours: 5.0,
            notes: null,
            status: 'pending',
            createdAt: new Date('2024-12-15T17:00:00').toISOString(),
            updatedAt: new Date('2024-12-15T17:00:00').toISOString(),
        },
        {
            userId: 6,
            date: '2024-12-18',
            serviceCategory: 'Videographer',
            eventType: 'Corporate',
            clientName: 'Finance Firm Retreat',
            venue: 'Riverside Hotel',
            startTime: '10:00',
            endTime: '16:00',
            totalHours: 6.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2024-12-18T10:00:00').toISOString(),
            updatedAt: new Date('2024-12-19T11:30:00').toISOString(),
        },
        {
            userId: 7,
            date: '2024-12-20',
            serviceCategory: 'Photographer',
            eventType: 'Wedding',
            clientName: 'Martinez Wedding',
            venue: 'Grand Ballroom',
            startTime: '14:30',
            endTime: '21:30',
            totalHours: 7.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2024-12-20T14:30:00').toISOString(),
            updatedAt: new Date('2024-12-21T08:00:00').toISOString(),
        },
        {
            userId: 2,
            date: '2024-12-23',
            serviceCategory: 'DJ',
            eventType: 'Wedding',
            clientName: 'Anderson Wedding',
            venue: 'Oak Tree Estate',
            startTime: '18:00',
            endTime: '00:00',
            totalHours: 6.0,
            notes: 'Backup equipment needed',
            status: 'pending',
            createdAt: new Date('2024-12-23T18:00:00').toISOString(),
            updatedAt: new Date('2024-12-23T18:00:00').toISOString(),
        },
        {
            userId: 3,
            date: '2024-12-27',
            serviceCategory: 'Videographer',
            eventType: 'Private Party',
            clientName: 'Sweet 16 Celebration',
            venue: 'Lakeview Manor',
            startTime: '19:00',
            endTime: '23:00',
            totalHours: 4.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2024-12-27T19:00:00').toISOString(),
            updatedAt: new Date('2024-12-28T10:45:00').toISOString(),
        },
        {
            userId: 4,
            date: '2024-12-30',
            serviceCategory: 'Photographer',
            eventType: 'Corporate',
            clientName: 'Marketing Team Event',
            venue: 'Downtown Convention Center',
            startTime: '11:00',
            endTime: '15:00',
            totalHours: 4.0,
            notes: null,
            status: 'pending',
            createdAt: new Date('2024-12-30T11:00:00').toISOString(),
            updatedAt: new Date('2024-12-30T11:00:00').toISOString(),
        },
        {
            userId: 5,
            date: '2025-01-03',
            serviceCategory: 'DJ',
            eventType: 'Wedding',
            clientName: 'Taylor Wedding',
            venue: 'City Hall Ballroom',
            startTime: '17:30',
            endTime: '23:30',
            totalHours: 6.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2025-01-03T17:30:00').toISOString(),
            updatedAt: new Date('2025-01-04T09:00:00').toISOString(),
        },
        {
            userId: 6,
            date: '2025-01-06',
            serviceCategory: 'Videographer',
            eventType: 'Wedding',
            clientName: 'Roberts Anniversary',
            venue: 'Garden Terrace',
            startTime: '15:00',
            endTime: '22:00',
            totalHours: 7.0,
            notes: 'Equipment setup took extra time',
            status: 'approved',
            createdAt: new Date('2025-01-06T15:00:00').toISOString(),
            updatedAt: new Date('2025-01-07T10:30:00').toISOString(),
        },
        {
            userId: 7,
            date: '2025-01-09',
            serviceCategory: 'Photographer',
            eventType: 'Other',
            clientName: 'Community Fundraiser',
            venue: 'Sunset Pavilion',
            startTime: '16:00',
            endTime: '20:00',
            totalHours: 4.0,
            notes: null,
            status: 'rejected',
            createdAt: new Date('2025-01-09T16:00:00').toISOString(),
            updatedAt: new Date('2025-01-10T13:15:00').toISOString(),
        },
        {
            userId: 2,
            date: '2025-01-11',
            serviceCategory: 'DJ',
            eventType: 'Wedding',
            clientName: 'Mitchell Wedding',
            venue: 'Heritage Hall',
            startTime: '18:00',
            endTime: '00:30',
            totalHours: 6.5,
            notes: 'Client requested overtime',
            status: 'pending',
            createdAt: new Date('2025-01-11T18:00:00').toISOString(),
            updatedAt: new Date('2025-01-11T18:00:00').toISOString(),
        },
        {
            userId: 3,
            date: '2025-01-14',
            serviceCategory: 'Videographer',
            eventType: 'Wedding',
            clientName: 'Phillips Wedding',
            venue: 'The Country Club',
            startTime: '13:00',
            endTime: '21:00',
            totalHours: 8.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2025-01-14T13:00:00').toISOString(),
            updatedAt: new Date('2025-01-15T08:30:00').toISOString(),
        },
        {
            userId: 4,
            date: '2025-01-17',
            serviceCategory: 'Photographer',
            eventType: 'Private Party',
            clientName: 'Robinson Retirement Party',
            venue: 'Riverside Hotel',
            startTime: '18:00',
            endTime: '22:00',
            totalHours: 4.0,
            notes: null,
            status: 'approved',
            createdAt: new Date('2025-01-17T18:00:00').toISOString(),
            updatedAt: new Date('2025-01-18T09:45:00').toISOString(),
        },
        {
            userId: 5,
            date: '2025-01-20',
            serviceCategory: 'DJ',
            eventType: 'Corporate',
            clientName: 'Sales Team Kickoff',
            venue: 'Grand Ballroom',
            startTime: '17:00',
            endTime: '21:30',
            totalHours: 4.5,
            notes: null,
            status: 'pending',
            createdAt: new Date('2025-01-20T17:00:00').toISOString(),
            updatedAt: new Date('2025-01-20T17:00:00').toISOString(),
        },
        {
            userId: 6,
            date: '2025-01-23',
            serviceCategory: 'Videographer',
            eventType: 'Wedding',
            clientName: 'Campbell Wedding',
            venue: 'Oak Tree Estate',
            startTime: '14:00',
            endTime: '22:30',
            totalHours: 8.5,
            notes: 'Additional coverage requested on-site',
            status: 'approved',
            createdAt: new Date('2025-01-23T14:00:00').toISOString(),
            updatedAt: new Date('2025-01-24T11:00:00').toISOString(),
        },
        {
            userId: 7,
            date: '2025-01-26',
            serviceCategory: 'Photographer',
            eventType: 'Wedding',
            clientName: 'Turner Wedding',
            venue: 'Lakeview Manor',
            startTime: '12:30',
            endTime: '20:00',
            totalHours: 7.5,
            notes: null,
            status: 'pending',
            createdAt: new Date('2025-01-26T12:30:00').toISOString(),
            updatedAt: new Date('2025-01-26T12:30:00').toISOString(),
        },
        {
            userId: 2,
            date: '2025-01-29',
            serviceCategory: 'DJ',
            eventType: 'Wedding',
            clientName: 'Parker Wedding',
            venue: 'City Hall Ballroom',
            startTime: '18:00',
            endTime: '23:00',
            totalHours: 5.0,
            notes: 'Travel delay due to traffic',
            status: 'approved',
            createdAt: new Date('2025-01-29T18:00:00').toISOString(),
            updatedAt: new Date('2025-01-30T10:15:00').toISOString(),
        },
    ];

    await db.insert(hourLogs).values(sampleHourLogs);
    
    console.log('✅ Hour logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});